"""empty message

Revision ID: 110d90b1fe30
Revises: db58eeeb5f10
Create Date: 2025-02-15 16:41:08.395085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110d90b1fe30'
down_revision = 'db58eeeb5f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('tag_name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('tag_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###
