"""empty message

Revision ID: 11235d38d64d
Revises: a9bfe99c105f
Create Date: 2025-02-22 19:22:48.275839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11235d38d64d'
down_revision = 'a9bfe99c105f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predefined_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predefined_task')
    # ### end Alembic commands ###
