"""empty message

Revision ID: 21f064a3bdfe
Revises: a9ddcfd6e080
Create Date: 2025-01-30 17:50:13.503079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f064a3bdfe'
down_revision = 'a9ddcfd6e080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('host_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'hosts', ['host_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('host_id')

    # ### end Alembic commands ###
