"""empty message

Revision ID: 35e06d440656
Revises: fcf536c1ccf9
Create Date: 2025-02-11 12:49:20.705785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35e06d440656'
down_revision = 'fcf536c1ccf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags_games_association_table',
    sa.Column('games_id', sa.Integer(), nullable=False),
    sa.Column('tags_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['games_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['tags_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('games_id', 'tags_id')
    )
    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favourite_game_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'games', ['favourite_game_id'], ['id'])
        batch_op.drop_column('image_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('favourite_game_id')

    op.drop_table('tags_games_association_table')
    # ### end Alembic commands ###
