"""empty message

Revision ID: a601dd68d5bc
Revises: aa3355d26c25
Create Date: 2025-02-07 12:10:05.977065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a601dd68d5bc'
down_revision = 'aa3355d26c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.drop_constraint('hosts_tournament_id_fkey', type_='foreignkey')
        batch_op.drop_column('tournament_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tournament_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('hosts_tournament_id_fkey', 'tournaments', ['tournament_id'], ['id'])

    # ### end Alembic commands ###
