"""empty message

Revision ID: a9bfe99c105f
Revises: a2296e5b170d
Create Date: 2025-02-22 19:10:12.041329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9bfe99c105f'
down_revision = 'a2296e5b170d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('task_summary')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_summary', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
