"""empty message

Revision ID: fcf536c1ccf9
Revises: c7dcfc3544d2
Create Date: 2025-02-11 11:48:17.147704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcf536c1ccf9'
down_revision = 'c7dcfc3544d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_favourites_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_favourites_id'], ['id'])

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('app_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('g2a_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('g2a_url', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('steam_price', sa.Float(), nullable=True))
        batch_op.drop_column('appId')
        batch_op.drop_column('steamPrice')
        batch_op.drop_column('g2aPrice')
        batch_op.drop_column('g2aUrl')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('g2aUrl', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('g2aPrice', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('steamPrice', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('appId', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('steam_price')
        batch_op.drop_column('g2a_url')
        batch_op.drop_column('g2a_price')
        batch_op.drop_column('app_id')

    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_favourites_id')

    # ### end Alembic commands ###
